version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount the application code for live-reloading during development
      - .:/app
      # Mount named volumes for persistent data
      - app-state:/app/state
      - app-kb:/app/kb_db
    environment:
      # Ensure python prints output immediately to the console
      - PYTHONUNBUFFERED=1
      # Path for the persistent Knowledge Base database
      - KB_PATH=/app/kb_db

  prometheus:
    image: prom/prometheus:v2.37.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:9.1.0
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  app-state:
  app-kb:
  grafana-storage:
