from prometheus_client import Counter, Gauge, Histogram

# --- General Metrics ---
BUGS_SUBMITTED = Counter(
    "triangulum_bugs_submitted_total",
    "Total number of bugs submitted to the supervisor"
)

BUGS_FIXED_SUCCESS = Counter(
    "triangulum_bugs_fixed_success_total",
    "Total number of bugs successfully fixed"
)

BUGS_FIXED_FAILURE = Counter(
    "triangulum_bugs_fixed_failure_total",
    "Total number of bugs that failed to be fixed",
    ["reason"] # e.g., 'max_cycles_reached', 'human_escalation'
)

# --- Supervisor / Runtime Metrics ---
ACTIVE_SESSIONS = Gauge(
    "triangulum_active_sessions",
    "Current number of active debugging sessions"
)

QUEUED_TICKETS = Gauge(
    "triangulum_queued_tickets",
    "Current number of bug tickets waiting in the scheduler"
)

BUG_FIX_DURATION_SECONDS = Histogram(
    "triangulum_bug_fix_duration_seconds",
    "Time taken to fix a bug from submission to completion",
    buckets=(30, 60, 120, 300, 600, 1800, 3600) # 30s to 1hr
)

# --- Agent-specific Metrics ---
LLM_CALLS = Counter(
    "triangulum_llm_calls_total",
    "Total number of calls made to the LLM",
    ["agent", "model"] # e.g., agent='Analyst', model='gpt-4'
)

PATCHES_GENERATED = Counter(
    "triangulum_patches_generated_total",
    "Total number of patches generated by the Analyst"
)

VERIFIER_CYCLES = Counter(
    "triangulum_verifier_cycles_total",
    "Total number of verification cycles (test runs) performed by the Verifier",
    ["patch_hash"]
)

SECURITY_SCAN_FAILED = Counter(
    "triangulum_security_scan_failed_total",
    "Total number of patches rejected due to security scans"
)
